version: '3.3'
services:
  fizz:
    build: ./fizz
    image: j00mz/fizz:latest
    environment:
     - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure

  redis:
    image: redis:alpine
    ports:
      - "6379"
    volumes:
      - db-data:/data
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  visualizer:
    image: marian/rebrow:latest
    ports:
      - "5001"
    depends_on:
      - redis
    links:
      - "redis"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
volumes:
  db-data: