apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: crawler
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: crawler
    spec:
      containers:
      - image: j00mz/crawltricks:latest
        name: crawltricks
        args: ["-u", "https://www.ebay.com", "-d", "2"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
