apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fizz
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: fizz
    spec:
      containers:
      - image: j00mz/fizz:latest
        name: fizz
