apiVersion: v1
kind: Service
metadata:
  name: fizz
spec:
  type: NodePort
  ports:
  - name: "fizz-service"
    port: 80
    targetPort: 8080
    nodePort: 31800
  selector:
    app: fizz
  
