apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: visualizer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: visualizer
    spec:
      containers:
      - image: marian/rebrow:latest
        name: visualizer
