apiVersion: v1
kind: Service
metadata:
  name: visualizer
spec:
  type: NodePort
  ports:
  - name: "visualizer-service"
    port: 5001
    targetPort: 5001
    nodePort: 31001
  selector:
    app: visualizer
  
